Figured out a way to give a nice error message
This way if we fail to parse old .env's folks should be able to figure
it out

diff --git a/bw-dev b/bw-dev
--- a/bw-dev
+++ b/bw-dev
@@ -1,9 +1,18 @@
 #!/bin/bash
 
-# import our ENV variables
-source .env
-
+# exit on errors
 set -e
+
+# import our ENV variables
+# catch exits and give a friendly error message
+function showerr {
+    echo "Failed to load configuration! You may need to update your .env and quote values with special characters in them."
+}
+trap showerr EXIT
+source .env
+trap - EXIT
+
+# show commands as they're executed
 set -x
 
 function clean {
